services:
  postgres:
    image: postgres:15.8-alpine
    ports:
      - "5432:5432"
    container_name: identity_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity-db
    volumes:
      - ./db/:/var/lib/postgresql/data
