services:
  postgres:
    image: postgres:15.8-alpine
    container_name: postgres_container
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity-db
    networks:
      - identity-network
    volumes:
      - ./db/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: api_container
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - identity-network

networks:
  identity-network:
    driver: bridge
