services:
  postgres:
    image: postgres:15.8-alpine
    container_name: identity_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity-db
    volumes:
      - ./db/:/var/lib/postgresql/data

  app:
    container_name: identity_container
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    depends_on:
      - postgres
